Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b8e3968ec50>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 136, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 3825
    1-diversity = 2
    2-diversity = 75
    3-diversity = 3748
  #Auts = 55
  #Isos = 1314
  1130896 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../relationaldef/main.py':

    2247843.631889      task-clock (msec)         #    0.833 CPUs utilized          
         6,511,715      context-switches          #    0.003 M/sec                  
         3,035,120      cpu-migrations            #    0.001 M/sec                  
       490,361,879      page-faults               #    0.218 M/sec                  
 5,777,403,730,039      cycles                    #    2.570 GHz                    
 4,841,464,365,587      instructions              #    0.84  insn per cycle         
   994,125,968,162      branches                  #  442.258 M/sec                  
    21,348,504,641      branch-misses             #    2.15% of all branches        

    2700.056308473 seconds time elapsed

