Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2b512d38ef98>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 136, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 4364
    1-diversity = 2
    2-diversity = 113
    3-diversity = 4249
  #Auts = 27
  #Isos = 740
  1069479 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../relationaldef/main.py':

    2264110.783951      task-clock (msec)         #    0.839 CPUs utilized          
         5,977,824      context-switches          #    0.003 M/sec                  
         2,898,123      cpu-migrations            #    0.001 M/sec                  
       478,011,530      page-faults               #    0.211 M/sec                  
 5,821,870,249,508      cycles                    #    2.571 GHz                    
 5,067,880,151,373      instructions              #    0.87  insn per cycle         
 1,040,376,233,088      branches                  #  459.508 M/sec                  
    20,888,081,072      branch-misses             #    2.01% of all branches        

    2700.074222445 seconds time elapsed

