Exception ignored in: <bound method MinionSol.__del__ of <minion.MinionSol object at 0x2ad3ece5b748>>
Traceback (most recent call last):
  File "/home/pventura/relationaldef/minion.py", line 132, in __del__
    if not self.EOF:
AttributeError: 'MinionSol' object has no attribute 'EOF'
Spectrum = [3, 2, 1]
CANCELLED

State before abort: 
  Diversity = 3794
    1-diversity = 4
    2-diversity = 87
    3-diversity = 3703
  #Auts = 3923
  #Isos = 25320
  1035616 calls to Minion

 Performance counter stats for 'timeout --signal=SIGINT 45m python3 ../../main.py':

     974714.955139      task-clock (msec)         #    0.361 CPUs utilized          
         6,957,037      context-switches          #    0.007 M/sec                  
         1,719,965      cpu-migrations            #    0.002 M/sec                  
       441,756,890      page-faults               #    0.453 M/sec                  
 5,302,156,925,257      cycles                    #    5.440 GHz                    
 4,291,740,429,153      instructions              #    0.81  insn per cycle         
   888,669,318,059      branches                  #  911.722 M/sec                  
    18,582,176,000      branch-misses             #    2.09% of all branches        

    2700.077261481 seconds time elapsed

